# Command to run yaml via launch file: ros2 launch robot_bringup control_only.launch.py 

# Name here should match the name of the node
rx200_moveit_control:
  ros__parameters:
    start_gripper_state: true
    x_start: -0.2
    y_start: 0.30
    z_start: 0.0
    x_target: 0.2
    y_target: -0.30
    z_target: 0.0
    